const express = require('express');
const cors = require('cors');
const multer = require('multer');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5001;
const CHAT_PASSWORD = process.env.CHAT_PASSWORD || 'arshi_admin_chat';

// Middleware
app.use(cors());
app.use(express.json());

// Multer storage in memory (no disk write, very clean)
const storage = multer.memoryStorage();
const upload = multer({ 
    storage: storage,
    limits: { fileSize: 10 * 1024 * 1024 } // 10MB limit
});

/**
 * 🔑 API Route: Validate Chat Password
 */
app.post('/api/login', (req, res) => {
    const { password } = req.body;
    if (password === CHAT_PASSWORD) {
        return res.json({ success: true, message: 'Authenticated successfully' });
    }
    return res.status(401).json({ success: false, message: 'Invalid password' });
});

/**
 * 💬 API Route: Send message to Gemini API (Text + Image support)
 */
app.post('/api/chat', upload.single('file'), async (req, res) => {
    try {
        const { password, message, history, systemInstruction } = req.body;

        // 1. Password Verification
        if (password !== CHAT_PASSWORD) {
            return res.status(401).json({ success: false, message: 'Unauthorized access' });
        }

        const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
        if (!GEMINI_API_KEY || GEMINI_API_KEY === 'your_gemini_api_key_here') {
            return res.status(500).json({ 
                success: false, 
                message: 'Gemini API Key is not configured. Please add your GEMINI_API_KEY in the backend/.env file.' 
            });
        }

        // 2. Prepare payload contents
        const contents = [];

        // Parse history if it comes as a string (due to multipart form-data)
        let parsedHistory = [];
        if (history) {
            try {
                parsedHistory = typeof history === 'string' ? JSON.parse(history) : history;
            } catch (e) {
                console.error('History parsing error:', e);
            }
        }

        // Add history to payload
        if (parsedHistory && parsedHistory.length > 0) {
            parsedHistory.forEach(item => {
                contents.push({
                    role: item.sender === 'user' ? 'user' : 'model',
                    parts: [{ text: item.text }]
                });
            });
        }

        // Prepare current user message parts
        const userParts = [];
        if (message) {
            userParts.push({ text: message });
        }

        // Handle uploaded file (image)
        if (req.file) {
            const base64Data = req.file.buffer.toString('base64');
            userParts.push({
                inlineData: {
                    mimeType: req.file.mimetype,
                    data: base64Data
                }
            });
        }

        // If no message text and no file, return error
        if (userParts.length === 0) {
            return res.status(400).json({ success: false, message: 'Empty message or file' });
        }

        contents.push({
            role: 'user',
            parts: userParts
        });

        // 3. System Instruction
        const defaultSystemInstruction = "You are a helpful and intelligent personal assistant. Answer accurately and clearly.";
        const activeSystemInstruction = systemInstruction || defaultSystemInstruction;

        // 4. Call Gemini 1.5 Flash API
        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`,
            {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    contents,
                    systemInstruction: {
                        parts: [{ text: activeSystemInstruction }]
                    },
                    generationConfig: {
                        temperature: 0.7
                    }
                })
            }
        );

        if (!response.ok) {
            const errData = await response.json();
            throw new Error(errData.error?.message || 'Gemini API Error');
        }

        const data = await response.json();
        const reply = data.candidates?.[0]?.content?.parts?.[0]?.text || "No response generated by the model.";

        return res.json({
            success: true,
            reply: reply.trim()
        });

    } catch (error) {
        console.error('Chat API Error:', error);
        return res.status(500).json({ success: false, message: error.message || 'Server error processing chat request' });
    }
});

// Start Server
app.listen(PORT, () => {
    console.log(`🚀 Chatbot backend running on http://localhost:${PORT}`);
});
